config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :meal_eatens, only: %i[index destroy edit update new create] do
    resources :posts, only: %i[new create]
  end

  resources :meals, only: %i[new create destroy edit update index show] do
    resources :foods, only: %i[create]
  end

  resources :foods, only: %i[destroy]

  resources :workout_sessions, only: %i[index destroy edit update new create show] do
    resources :posts, only: %i[new create]
  end

  resources :workouts, only: %i[create destroy edit update show] do
    resources :workout_exercises, only: %i[new create]
  end

  resources :workout_exercises, only: %i[edit update destroy]

  resources :posts, only: %i[show destroy index] do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end

  resources :chatrooms, only: %i[show index] do
    resources :messages, only: %i[create destroy]
  end

  resources :users, only: %i[] do
    resources :chatrooms, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :user1, class_name: "User"
  belongs_to :user2, class_name: "User"

  def users
    [user1, user2]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :meal
  validates :name, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :post_id, uniqueness: { scope: :user }
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_many :foods

  validates :name, presence: true

  def total_carbs
    total = 0
    foods.each do |food|
      total += food.carbs
    end
    total
  end

  def total_proteins
    total = 0
    foods.each do |food|
      total += food.protein
    end
    total
  end

  def total_fats
    total = 0
    foods.each do |food|
      total += food.fats
    end
    total
  end

  def total_calories
    total = 0
    foods.each do |food|
      total += food.calories
    end
    total
  end
end

app/models/meal_eaten.rb
class MealEaten < ApplicationRecord
  belongs_to :meal
  belongs_to :user
  validates :date, presence: true
  validates :meal_type, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :photo
  validates :photo, attached: true
  has_many :likes
end

app/models/read.rb
class Read < ApplicationRecord
  belongs_to :user
  belongs_to :meassage
end

app/models/user.rb
require 'date'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :meals
  has_many :meal_eatens
  has_many :workouts
  has_many :workout_sessions
  has_many :exercises
  has_many :chats1, class_name: "Chatroom", foreign_key: :user1_id
  has_many :chats2, class_name: "Chatroom", foreign_key: :user2_id
  validates :username, presence: true

  def not_messaged
    messaged = chatrooms.map do |chat|
      chat.users[0] == self ? chat.users[1].id : chat.users[0].id
    end
    messaged << id
    User.where.not(id: messaged)
  end

  def chatrooms
    [chats1, chats2].flatten
  end

  def days_meals
    meal_eatens.where(date: Date.today)
  end

  def days_calories
    total = 0
    days_meals.each { |m| total += m.meal.total_calories }
    total
  end

  def days_protiens
    total = 0
    days_meals.each { |m| total += m.meal.total_proteins }
    total
  end

  def days_fats
    total = 0
    days_meals.each { |m| total += m.meal.total_fats }
    total
  end

  def days_carbs
    total = 0
    days_meals.each { |m| total += m.meal.total_carbs }
    total
  end
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :workout_exercises, dependent: :destroy
  has_many :exercises, through: :workout_exercises

  validates :name, presence: true
  validates :workout_type, presence: true
end

app/models/workout_exercise.rb
class WorkoutExercise < ApplicationRecord
  belongs_to :workout
  validates :sets, presence: true
  validates :reps, presence: true
end

app/models/workout_session.rb
class WorkoutSession < ApplicationRecord
  belongs_to :user
  belongs_to :workout
  validates :time, presence: true
end

app/controllers/foods_controller.rb
require "json"
require "rest-client"

class FoodsController < ApplicationController

  def create
    authorize Food
    @meal = Meal.find(params[:meal_id])
    @food = Food.new(food_params)
    query = food_api(@food.name)
    @food.name = query["name"]
    @food.carbs = query["carbohydrates_total_g"]
    @food.protein = query["protein_g"]
    @food.fats = query["fat_total_g"]
    @food.calories = query["calories"]
    @food.meal = @meal
    if @food.save
      redirect_to meal_path(@meal)
    else
      render meal_path(@meal)
    end
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
    authorize food
    redirect_to meal_path(food.meal)
  end

  private

  def food_api(query)
    response = RestClient.get("https://api.calorieninjas.com/v1/nutrition?query=#{query}", headers={'X-Api-Key': ENV["FOOD_API_KEY"]})
    JSON.parse(response)['items'][0]
  end

  def food_params
    params.require(:food).permit(:name)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    authorize Like
    Like.create!(post_id: params[:post_id], user_id: current_user.id)
  end

  def destroy
    like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    authorize like
    like.destroy
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def new
    @meal = Meal.new
    authorize @meal
  end

  def create
    authorize Meal
    @meal_eaten = MealEaten.new
    @meal = Meal.new(meal_params)
    @meal.user = current_user
    if @meal.save
      redirect_to meal_path(@meal)
    else
      render new_meal_eaten_path
    end
  end

  def show
    @food = Food.new
    @meal = Meal.find(params[:id])
    authorize @meal
  end

  private

  def meal_params
    params.require(:meal).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    user_signed_in? ? (redirect_to posts_path) : (redirect_to new_user_session_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = policy_scope(Post)
    @like = Like.new
    @chatrooms = policy_scope(Chatroom)
    @other_users = current_user.not_messaged
  end

  def new
    if params[:workout_session_id].present?
    @source = WorkoutSession.find(params[:workout_session_id])
    @path = workout_session_path(@source)
    else
      @source = MealEaten.find(params[:meal_eaten_id])
      @path = meal_eaten_path(@source)
    end
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    authorize @post
    @post.user = current_user
    if @post.save
      if params[:workout_session_id].present?
        redirect_to workout_session_path(params[:workout_session_id])
      else
        redirect_to meal_eatens_path
      end
    elsif params[:workout_session_id].present?
      redirect_to new_workout_session_post_path(params[:workout_session_id])
    else
      redirect_to new_meal_eaten_post_path(params[:meal_eaten_id])
    end
  end

  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
    authorize @post
  end

  private

  def post_params
    params.require(:post).permit(:caption, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def liked?(post)
    Like.exists?(post: post, user: current_user)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <title>Dynami - Get fit. Get social</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta property="og:title" content="Dynami - Get fit. Get social" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="https://cdn10.phillymag.com/wp-content/uploads/sites/3/2021/10/fit-academy-1200x630-1.jpg"/>
    <meta property="og:description" content="Keep track of your nutrition intake and your workouts whist also keeping up with friends" />
    <meta property="og:site_name" content="Dynami - Get fit. Get social" />
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
    </style>
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Genos:ital,wght@1,600&family=Merriweather&family=Roboto:wght@400;500&display=swap');
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:wght@900&display=swap');
    </style>
  </head>

  <body data-controller="hello">
    <% if user_signed_in?  %>
      <%= render 'shared/header' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="hero_banner">
  <div class="title">
    <h2>Welcome <%= current_user.username %></h2>
    <h4>Here Are Your Totals For The Day...</h4>
  </div>
  <div class="nutrition-cards">
    <div class="n-card">
      <%= render "shared/progress", progress: (current_user.days_carbs.fdiv(300)), classes: 'mr-3' %>
      <div class="n-card-heading">
      <%# <i class="fas fa-bread-slice"></i> %>
      <h4>Carbohydrates</h4>
      <p><%= current_user.days_carbs %><span>g.</span></p>
      </div>
    </div>

    <div class="n-card">
      <%= render "shared/progress", progress: (current_user.days_fats.fdiv(100)) , classes: 'mr-3' %>
      <div class="n-card-heading">
      <%# <i class="fas fa-bread-slice"></i> %>
      <h4>Fats</h4>
      <p><%= current_user.days_fats %><span>g.</span></p>
      </div>
    </div>

    <div class="n-card">
      <%= render "shared/progress", progress: (current_user.days_protiens.fdiv(200)), classes: 'mr-3' %>
      <div class="n-card-heading">
      <%# <i class="fas fa-bread-slice"></i> %>
      <h4>Proteins</h4>
      <p><%= current_user.days_protiens %><span>g.</span></p>
      </div>
    </div>

    <div class="n-card">
      <%= render "shared/progress", progress: (current_user.days_calories.fdiv(2000)), classes: 'mr-3' %>
      <div class="n-card-heading">
      <%# <i class="fas fa-bread-slice"></i> %>
      <h4>Calories</h4>
      <p><%= current_user.days_calories %></p>
      </div>
    </div>
    <%# <%= render "posts/circles", progress: 40  %>
  </div>
</div>

app/views/shared/_chats.html.erb
<% @chatrooms.each do |chatroom| %>
  <%= link_to chatroom_path(chatroom) do %>
  <div class="chat-card">
    <div class="chat-user">
      <img class="h-8 w-8 rounded-full" src=<%= chatroom.users.find { |u| u != current_user}.avatar_url %> alt="">
      <div class="chat-name">
        <p><%= chatroom.users.find { |u| u != current_user}.username %> </p>
        <% if chatroom.messages.count > 0 %>
          <span><%= chatroom.messages.last.content %></span>
        <% end %>
        </div>

        <div class="chat-preview">
        <% if chatroom.messages.count > 0 %>
          <span><%= chatroom.messages.last.created_at.strftime("%l:%M%p") %></span>
        <% end %>
        </div>
    </div>
  </div>
  <%end %>
<%end %>

app/views/shared/_exercises.html.erb
  <% exercises.each do |workout_log|  %>
<div class="ex-card">
    <div class="ex-card-body">
      <div class="top-line-ws">
        <h4><%= "#{workout.name}" %>  -  <%= "#{workout.workout_type}" %></h4>
      </div>
      <div>
        <div class="exercise_card_heading">
            <p class = "exercise_name"><%= "Exercise: #{workout_log.name}" %></p>
            <div class = "info">
              <p class= "information"><b>Reps:</b><span><%="#{workout_log.reps}"%></span></p>
              <p class= "information"><b>Sets:</b><span><%="#{workout_log.sets}"%></span></p>
              <p class= "information"><b>Weight:</b><span><%="#{workout_log.weight}"%></span></p>
            </div>
        </div>
      </div>
    </div>
</div>
  <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_foods.html.erb
<% foods.each do |food|  %>
  <div class="food-card-body">
    <div class="food-card">
      <div class = "food_name">
        <h2><%= " #{food.name}" %></h2>
      </div>
      <div class="flex-container">
        <div class="flex-child magenta">
          <div class="card-heading">
            <% total =  food.carbs + food.protein + food.fats %>
              <p><%= "Carbs: #{food.carbs}g" %></p>
              <div class = "carbs_line">
              <% carbs_total = food.carbs.fdiv(total) * 100%>
                <div class = "carbs_percent" style = "width:<%=carbs_total%>%;">
                </div>
              </div>
              <p><%= "Proteins: #{food.protein}g" %></p>
              <div class = "protein_line">
               <% protein_total = food.protein.fdiv(total) * 100 %>
                <div class = "protein_percent" style = "width:<%=protein_total%>%;">
                </div>
              </div>
              <p><%= "Fats: #{food.fats}g" %></p>
              <div class = "fats_line">
              <% fats_total = food.fats.fdiv(total) * 100%>
                <div class = "fats_percent" style = "width:<%=fats_total%>%;">
                </div>
              </div>
          </div>
        </div>
          <p class = "calories"><%= "Calories: #{food.calories} cals"%></p>
          <p><%= link_to "Delete this food", food_path(food), method: :delete, class:"delete_food_button" %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav>
  <div class="logo">
    <h4>DYNAMI</h4>
  </div>
      <ul class="nav-links">
        <div class="link-container">
          <li>
            <%= link_to root_path, class: "link" do %>
              <i class="fas fa-home"></i>
            <% end %>
          </li>
        </div>

        <div class="link-container">
          <li >
            <%= link_to workout_sessions_path, class: "link" do %>
              <i class="fas fa-dumbbell"></i>
            <% end %>
          </li>
        </div>

        <div class="link-container">
          <li >
            <%= link_to meal_eatens_path, class: "link" do %>
              <i class="fas fa-utensils"></i>
            <% end %>
          </li>
        </div>

        <div class="link-container">
          <li >
            <%= link_to chatrooms_path, class: "link" do %>
              <i class="fas fa-comments"></i>
            <% end %>
          </li>
        </div>
      </ul>

      <div class="log-out">
        <li >
          <%= link_to destroy_user_session_path, class: "link", method: :delete do %>
            <i id="log-out-icon" class="fas fa-sign-out-alt"></i>
          <% end %>
        </li>
      </div>
      <div class="burger">
        <div class="line1"></div>
        <div class="line2"></div>
        <div class="line3"></div>
      </div>
</nav>

app/views/shared/_posts.html.erb
<div class= "card-container">
  <% @posts.each do |post| %>
  <div>
    <div class = "postpage">
      <div class="post-user">
        <img class="h-8 w-8 rounded-full" src=<%= post.user.avatar_url %> alt="">
        <h2 class="h2_new"><%= post.user.username%></h2>
      </div>
      <%= link_to post_path(post) do %>
        <%= cl_image_tag post.photo.key, height: 300, width: 400, crop: :fill, class:"post_page_card_image" %>
      <% end %>
      <ul class = "list-inline">
        <li>
          <div class="like_subscribe <%= "liked" if liked?(post) %>" data-post-id="<%= post.id %>">
          <% if liked?(post) %>
            <i class="fas fa-heart"></i>
          <% else %>
            <i class="far fa-heart"></i>
          <% end %>
          </div>
        </li>
        <li>
        <%= link_to  post_path(post) do %>
          <div class="comments">
            <i class="far fa-comments"></i>
          </div>
        <% end %>
        </li>
        <li>
          <div class="share_icon">
            <i class="far fa-paper-plane"></i>
          </div>
        </li>
        <li>
          <div class="bookmark_icon">
            <i class="far fa-bookmark"></i>
          </div>
        </li>
      </ul>

    <div class="bottom_half">
        <div class="likedby">
          <% if post.likes.count >= 1  %>
            <p><%= pluralize post.likes.count, "like" %></p>
          <% end %>
        </div>


        <div class= "user_caption">
          <strong><p><%= post.user.username %> - </strong><%= post.caption %></p>
        </div>
        <div class = "new_comments">
          <% comment = post.comments.last %>
          <% if comment %>
            <div class= "post_comments">
              <strong><p><%= comment.user.username %></strong> <span><%= comment.content %></span></p>
            </div>
            <br>
          <% end  %>
          <% if post.comments.count > 1 %>
            <div class= "post_comments">
              <%= link_to "See more comments (#{post.comments.count - 1})", post_path(post) %>
            </div>
          <% end %>
          <div class="posted-at">
            <p>Posted at <%= post.created_at.strftime("%l:%M%p") %> on the <%= post.created_at.strftime("%d/%m/%C")  %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_progress.html.erb
<% classes ||= "" %>
<div id="progress" data-progress="<%= progress %>" class="<%= classes %>" ></div>

app/views/shared/_sign_in.html.erb
<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-inputs text-xlg dynami-login-form">
    <%= f.input :email,
                required: false,
                autofocus: true,
                # input_html: { autocomplete: "email" },
                label: false,
                placeholder: "email" %>
    <%= f.input :password,
                required: false,
                # input_html: { autocomplete: "current-password" },
                label: false,
                placeholder: "password" %>
    <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
  </div>

<%= button_tag(type: 'submit', class: 'group relative w-full flex justify-center py-2 px-4 border border-transparent text-xlg font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dynami-login') do %>
      Log in
    <% end %>
<% end %>

app/views/shared/_users.html.erb
<% @other_users.each do |user| %>
  <%= link_to user_chatrooms_path(user), method: 'post' do %>
    <div class="chat-card">
      <div class="chat-user">
        <img class="h-8 w-8 rounded-full" src=<%= user.avatar_url %> alt="">
        <p><%= user.username %> </p>
      </div>
    </div>
  <%end %>
<%end %>