config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :meal_eatens, only: %i[index destroy edit update new create] do
    resources :posts, only: %i[new create]
  end

  resources :meals, only: %i[new create destroy edit update index show] do
    resources :foods, only: %i[create]
  end

  resources :foods, only: %i[destroy]

  resources :workout_sessions, only: %i[index destroy edit update new create show] do
    resources :posts, only: %i[new create]
  end

  resources :workouts, only: %i[create destroy edit update show] do
    resources :workout_exercises, only: %i[new create]
  end

  resources :workout_exercises, only: %i[edit update destroy]

  resources :posts, only: %i[show destroy index] do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end

  resources :chatrooms, only: %i[show index] do
    resources :messages, only: %i[create destroy]
  end

  resources :users, only: %i[] do
    resources :chatrooms, only: %i[create]
  end
end

app/models/meal_eaten.rb
class MealEaten < ApplicationRecord
  belongs_to :meal
  belongs_to :user
  validates :date, presence: true
  validates :meal_type, presence: true
end

app/controllers/meal_eatens_controller.rb
class MealEatensController < ApplicationController

  def index
    @meal_eatens = policy_scope(MealEaten)
  end

  def new
    @meal = Meal.new
    @meal_eaten = MealEaten.new
    authorize @meal_eaten
  end

  def create
    @meal = Meal.new
    @meal_eaten = MealEaten.new(meal_eaten_params)
    authorize MealEaten
    @meal_eaten.user = current_user
    if @meal_eaten.save
      redirect_to new_meal_eaten_post_path(@meal_eaten)
    else
      render :new
    end
  end

  def destroy
    meal = MealEaten.find(params[:id])
    authorize meal
    meal.destroy
    redirect_to meal_eatens_path
  end

  private

  def meal_eaten_params
    params.require(:meal_eaten).permit(:date, :meal_type, :meal_id)
  end
end

app/views/meal_eatens/index.html.erb
<div class="back-button-container">
<%= link_to root_path, class: "btn-back" do %>
  <i class="far fa-arrow-alt-circle-left"></i>
<% end %>
</div>

<div class="food-container food-title">
  <h2>Your Food Log</h2>
  <%= link_to "Log A New Food", new_meal_eaten_path, class: "new-btn"  %>
</div>
<div class="food-container">
  <% @meal_eatens.each do |meal| %>
    <div class="me-card-container">
      <div class="me-card">
            <div class="card-heading">
              <div>
                <div class="top-line">
                  <h4 class="meal-type"><%= meal.meal_type %></h4>
                  <%= link_to meal_eaten_path(meal.id), method: :delete do %>
                    <i class="far fa-trash-alt"></i>
                  <% end %>
                </div>
                <h2 class="heading"><%= meal.meal.name %></h2>
                <%= meal.date %>
              </div>
              <div class= "info">
                <p class="information" ><b>Total Carbs: </b><span><%= meal.meal.total_carbs %></span></p>
                <p class="information" ><b>Total Protein: </b><span><%= meal.meal.total_proteins %></span></p>
                <p class="information" ><b>Total Fats: </b><span><%= meal.meal.total_fats %></span></p>
                <p class="information" ><b>Total Calories: </b><span><%= meal.meal.total_calories %></span></p>
              </div>
            </div>
            <div>
                <%= link_to "details", meal_path(meal.meal), class: "details" %>
            </div>
            <%# <div class="ed-buttons">
            <p class="edit-btn">Edit</p>
            <p class="delete-btn">Delete</p>
            </div> %>
        </div>
    </div>
    <% end %>

</div>

app/views/meal_eatens/new.html.erb
<div class="back-button-container">
<%= link_to meal_eatens_path, class: "btn-back" do %>
  <i class="far fa-arrow-alt-circle-left"></i>
<% end %>
</div>

<div class="me-new-heading">
  <h2>Log a New Meal</h2>
</div>

<div class="container new_meal_session">
  <%= simple_form_for(@meal_eaten) do |f| %>
    <%= f.association :meal, collection: current_user.meals, prompt: 'Select a meal'%>
    <%= f.input :meal_type, prompt: "What type of meal is this?" %>
    <%= f.input :date %>
    <%= f.submit value: 'Add this meal!', class:'btn btn-primary' %>
  <% end %>
</div>

<div class="me-new-heading">
  <h2>Log a New Food</h2>
</div>

<div class="container new_meal_session">
  <%= simple_form_for(@meal) do |f| %>
    <%= f.input :name %>
    <%= f.submit value: 'Name this meal', class:'btn btn-primary' %>
  <% end %>
</div>

app/views/meal_eatens/tmp.html.erb
<div class="back-button-container">
<%= link_to root_path, class: "btn-back" do %>
  <i class="far fa-arrow-alt-circle-left"></i>
<% end %>
</div>

<div class="wsheading">
  <h2>Your Workouts</h2>
</div>

<% @workout_sessions.each do |workout_session| %>

<div class="ws-card-container">
  <div class="ws-card">
        <div class="ws-card-heading">
          <%= link_to workout_session_path(workout_session), method: :delete do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
          <h2 class="ws-heading"><%="#{workout_session.workout.name}" %></h2>
          <i id="weight" class="fas fa-weight-hanging"></i>
          <h3><%= "#{workout_session.workout.workout_type}" %></h3>
          <%= link_to "details", workout_session_path(workout_session), class: "details" %>
        </div>
    </div>
</div>
<% end %>


<h4 class="ws-new"><%= link_to "Add A New Workout Session", new_workout_session_path %></h4>