config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :meal_eatens, only: %i[index destroy edit update new create] do
    resources :posts, only: %i[new create]
  end

  resources :meals, only: %i[new create destroy edit update index show] do
    resources :foods, only: %i[create]
  end

  resources :foods, only: %i[destroy]

  resources :workout_sessions, only: %i[index destroy edit update new create show] do
    resources :posts, only: %i[new create]
  end

  resources :workouts, only: %i[create destroy edit update show] do
    resources :workout_exercises, only: %i[new create]
  end

  resources :workout_exercises, only: %i[edit update destroy]

  resources :posts, only: %i[show destroy index] do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end

  resources :chatrooms, only: %i[show index] do
    resources :messages, only: %i[create destroy]
  end

  resources :users, only: %i[] do
    resources :chatrooms, only: %i[create]
  end
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_many :foods

  validates :name, presence: true

  def total_carbs
    total = 0
    foods.each do |food|
      total += food.carbs
    end
    total
  end

  def total_proteins
    total = 0
    foods.each do |food|
      total += food.protein
    end
    total
  end

  def total_fats
    total = 0
    foods.each do |food|
      total += food.fats
    end
    total
  end

  def total_calories
    total = 0
    foods.each do |food|
      total += food.calories
    end
    total
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def new
    @meal = Meal.new
    authorize @meal
  end

  def create
    authorize Meal
    @meal_eaten = MealEaten.new
    @meal = Meal.new(meal_params)
    @meal.user = current_user
    if @meal.save
      redirect_to meal_path(@meal)
    else
      render new_meal_eaten_path
    end
  end

  def show
    @food = Food.new
    @meal = Meal.find(params[:id])
    authorize @meal
  end

  private

  def meal_params
    params.require(:meal).permit(:name)
  end
end

app/views/meals/new.html.erb
<h2>Search for a food </h2>

app/views/meals/show.html.erb
<%= link_to meal_eatens_path, class: "btn-back" do %>
<i class="fas fa-arrow-left"></i>
<% end %>

<div class="meal_show_container">
  <div class="wsheading">
    <h2><%= "#{@meal.name}"%></h2>
  </div>
  <%= render "shared/foods", foods: @meal.foods %>
  <div class = "add_form_simple">
      <%= simple_form_for([@meal, @food]) do |f| %>
      <div class="d-flex align-items-center">
        <%= f.input :name, wrapper_html: { class: "flex-grow-1 p-2 mb-0" }, label: false %>
        <%= f.submit value: 'Add a food', class:'btn btn-primarys' %>
      </div>
      <% end %>
  </div>
<div class="continue-d">
  <%= link_to "Continue", new_meal_eaten_path, class: "continue"  %>
</div>
</div>